### ISSUE TITLE
touch screen

### ISSUE THREAD

**Issue by ghost** [SkyrilHD/Dell-E7250-Hackintosh#12]
Hi,
I've got the 1080p touch-screen version of the E7250. Is there a kext to enable touch screen on the hackintosh?

**Comment by SkyrilHD** [comment]
Hi,

it is possible. But is it time consuming? Yes. Do I have the 1080p version? No. The only thing I could do is doing a special EFI for touchscreen laptops. But since I don't have the touch screen model, there is no way I could debug it.

I will send na EFI after I know how to add touch screen support.

**Comment by SkyrilHD** [comment]
Can you try this EFI?

[EFI.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/5461416/EFI.zip)

**Comment by ghost** [comment]
it says: OCB: LoadImage failed: security violation

**Comment by SkyrilHD** [comment]
This is because Apple Secure Boot is missing... The EFI below has Secure Boot disabled.

[EFI 2.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/5461510/EFI.2.zip)

**Comment by ghost** [comment]
How can I change the efi without booting macos? Sorry I'm quite noob

**Comment by SkyrilHD** [comment]
ehhh... with another computer... put the efi on an USB-Stick that is formatted as FAT32

**Comment by ghost** [comment]
ok i try thanks

**Comment by ghost** [comment]
It's working fine! Thanks dude

**Comment by SkyrilHD** [comment]
No problem! I will keep this in mind and will push it to the repo... Thanks for testing
