### ISSUE TITLE
Intel WiFi & BT not working

### ISSUE THREAD

**Issue by n2ng-dev** [SkyrilHD/Dell-E7250-Hackintosh#21]
Hii

Thanks for ur awesome works, overall work very well.
In my case network not found, and Bluetooth cant turn on.

Dell 7250
MacOS Big Sur 11.2.2
OpenCore 0.6.7
Intel Dual Wifi-AC 7265

See attach

Many Thanks 

![image](https://user-images.githubusercontent.com/12078569/110417349-032c9500-80c8-11eb-99fb-bbce1ee2acbc.png)

**Comment by SkyrilHD** [comment]
Did you turn on AirportItlwm, IntelBluetoothInjector and IntelBluetoothFirmware in the config?

**Comment by n2ng-dev** [comment]
Of course

Yeah Don't know why now Bluetooth work fine
(Bluetooth work after sleep)
But Network still not found

Please see attach


Thanks![image](https://user-images.githubusercontent.com/12078569/110447212-94186600-80f2-11eb-846b-0c83ba9dc248.png)

**Comment by SkyrilHD** [comment]
Can you export an IOReg and send it here?
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-302.zip

**Comment by n2ng-dev** [comment]
this IOReg from after sleep & after reboot..

please see attach..

Thanks
[IOReg.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/6113002/IOReg.zip)

**Comment by SkyrilHD** [comment]
ok since the kexts loads, I don't think it has issues with the EFI itself but you seem to have issues with the AirportItlwm kext.

Download v1.3.0-alpha from here: https://github.com/OpenIntelWireless/itlwm/releases and replace the AirportItlwm kext with the one I provided.

If it still does not work then make an issue on https://github.com/OpenIntelWireless/itlwm since the problem is not from the EFI which I cannot fix on my side
