### ISSUE TITLE
TrackPad setting not working in Sierra 

### ISSUE THREAD

**Issue by rajmahavir76** [SkyrilHD/Dell-E7250-Hackintosh#30]
Thanks a lot for EFI

Please help
Dell E7250 Trackpad(shows searching for bluetooth trackpad) & battery status not working in Sierra.

**Comment by SkyrilHD** [comment]
For battery: SMCBatteryManager does not work on Sierra, reference to https://github.com/acidanthera/bugtracker/issues/1114
Solution: Switch to ACPIBatteryManager

For trackpad: I honestly have no idea, as for requirements it says it supports every release since 10.6. I think the kext needs to be rewritten. Maybe (just maybe) it gets fixed when battery is recognised probably.

**Comment by SkyrilHD** [comment]
Any update?
