### ISSUE TITLE
Noob question regarding wireless

### ISSUE THREAD

**Issue by nickogaidarov** [SkyrilHD/Dell-E7250-Hackintosh#38]
Hello, guys! Luckily i managed to partition my hard drive and install Big Sur. Everything works amazing except the wireless which i've read that is disabled by default. As the title says i am a complete noob and i have no idea how to enable it :( Shall i use OpenCore Configurator or something else? Thank you in advance! Keep up the great work!

**Comment by SkyrilHD** [comment]
Enabling WiFi is actually pretty easy (even TextEdit should be enough). The only thing you need to change is Enabled: you just have to put it from false to true.

This is the line:
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L876

**Comment by nickogaidarov** [comment]
Solved! Replaced all wifi related lines from false to true. Wifi works and get's connected but says No internet connection... :(

**Comment by nickogaidarov** [comment]
Thank you, SkyrilHD for your amazing work! Have you experienced the No internet connection issue mentioned above?

**Comment by SkyrilHD** [comment]
You could try using [itlwm](https://github.com/OpenIntelWireless/itlwm/releases) (which needs [HeliPort](https://github.com/OpenIntelWireless/HeliPort/releases) app) instead of AirportItlwm (which is the native way).

Could you check your router settings like if 802.11w and WPA3 are disabled?

EDIT: Copy the itlwm.kext to OC>Kexts and change the followings in the config:
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L872
and
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/blob/06b1ba7cf36cbb1d4b093de18eb30c54f5cfec2b/OpenCore/EFI/OC/config.plist#L878

Just replace AirportItlwm with itlwm

**Comment by nickogaidarov** [comment]
Thank you, again! Everything's solved!
