### ISSUE TITLE
[BUG] Sleep doesn't work on charger and/or as long as something is connected

### ISSUE THREAD

**Issue by SkyrilHD** [SkyrilHD/Dell-E7250-Hackintosh#6]
So, this bug happens on Clover and OpenCore...

Sleep works fine on battery if nothing is connected (USB). But as soon as the charger is plugged in or any USB is connected sleep will not work.

Extracting the logs shows this:

`2020-05-07 18:05:57 +0200 DarkWake            	DarkWake from Normal Sleep [CDN] : due to LID0/ Using BATT (Charge:36%) 6 secs`
`2020-05-07 18:06:10 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to LID0/Lid Open Using BATT (Charge:36%)`

Any help is appreciated.

**Comment by SkyrilHD** [comment]
Sleep is now fixed in the latest commit

**Comment by AtharvShinde** [comment]
How you fix sleep when charging ???

**Comment by SkyrilHD** [comment]
https://github.com/SkyrilHD/Dell-E7250-Hackintosh/commit/61b075f7ed6f4963c2dfc2e549175b00c0325967

**Comment by AtharvShinde** [comment]
Using mi notebook 14 and facing same issue

**Comment by SkyrilHD** [comment]
Follow this guide then: https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html

**Comment by Razzamatazz777** [comment]
Hi @SkyrilHD, 
Using your 0.7.2 release, confirmed sleep works on battery, whether or not something is connected to USB.

However, it will still DarkWake from Normal Sleep shortly after closing the lid if the AC charger is plugged in. Does not matter if something is connected to USB. USBMap has been enabled, per your readme, with no difference. 

Any thoughts? Thanks.

`2021-08-18 15:25:18 -0600 DarkWake            	DarkWake from Normal Sleep [CDNP] : due to LID0/ Using AC (Charge:100%) 21 secs   
2021-08-18 15:25:18 -0600 WakeDetails         	DriverReason:XHC - DriverDetails:                                          
2021-08-18 15:25:18 -0600 HibernateStats      	hibmode=3 standbydelaylow=10800 standbydelayhigh=86400`

**Comment by SkyrilHD** [comment]
Did you disable USBInjectAll, FakePCIID and FakePCIID_XhciMux as well?

Also, don't forget to disable XhciPortLimit which is necessary for 11.3+

**Comment by Razzamatazz777** [comment]
FakePCIID_XhciMux wasn't, but I just disabled it and still no difference. Confirmed the rest were previously disabled. Thanks.

**Comment by SkyrilHD** [comment]
hmm that's very weird. Check you did not disable the GPRW Patches (which are the main reason sleep works) I suggest to restore the power management settings to default by typing this in Terminal: `pmset restoredefaults`

**Comment by Razzamatazz777** [comment]
I finally got it working. I had to ensure the BIOS setting for Wake on LAN/WLAN (in addition to USB Wake Support) was disabled. Then pmset restoredefaults. Thanks for your help.
