### ISSUE TITLE
Dell Wireless 5809e not working on Monterey 12.3.1

### ISSUE THREAD

**Issue by mrstimpee** [SkyrilHD/Dell-E7250-Hackintosh#60]
I think, with the implementation of UTB Map and the USB Tool Box, the WWAN Card ist not seen anymore. could that be?

**Comment by SkyrilHD** [comment]
The WWAN was definitely working on Big Sur but since Monterey, I have not been able to get it working even though the card is recognised properly. I don't exactly know what Apple changed in their WWAN kexts but they broke it.

**Comment by mrstimpee** [comment]
Mine is working on Monterey 12.3.1. with OC Rel. 0.76 2021-12-05. 
It is connected via USB 3.0 Bus, so that's why I think the problem has to be in the UTB Map or the Tool Box. :) 

![Bildschirmfoto 2022-05-02 um 11 17 05](https://user-images.githubusercontent.com/104754594/166212866-bc3efad9-820d-47c2-b3cb-3ac0c84541de.png)
![Bildschirmfoto 2022-05-02 um 11 17 18](https://user-images.githubusercontent.com/104754594/166213135-a2f2c407-3c32-4427-83c1-dbcd03633bdb.png)
![Bildschirmfoto 2022-05-02 um 11 18 33](https://user-images.githubusercontent.com/104754594/166213234-d6d83049-641d-4335-8122-94434d916d69.png)
![Bildschirmfoto 2022-05-02 um 11 18 10](https://user-images.githubusercontent.com/104754594/166213263-9734912b-2a8b-43e9-aaee-bf9579acb0ed.png)

**Comment by SkyrilHD** [comment]
Oh wow. Will definitely try to fix it. Thanks for the heads up!

**Comment by SkyrilHD** [comment]
Can you try this kext (remove USBToolBox and UTBMap first)? I have got the card detecting, but I cannot connect to any network (Telekom and Vodafone). I am guessing because the 3G networks are shut down here in Germany (?)
[USBMap.kext.zip](https://github.com/SkyrilHD/Dell-E7250-Hackintosh/files/8825734/USBMap.kext.zip)

I am getting this error:
![image](https://user-images.githubusercontent.com/28839925/171677662-8729eb92-17f3-420f-a9d3-eb8e5dcd65b2.png)
