### ISSUE TITLE
trackpad gestures

### ISSUE THREAD

**Issue by ghost** [SkyrilHD/Dell-E7250-Hackintosh#8]
Hi,
I have installed Catalina with your EFI and it's working all fine, but trackpad gestures aren't working. Is there any fix?

**Comment by SkyrilHD** [comment]
Which EFI did you use?

**Comment by ghost** [comment]
Clover

**Comment by SkyrilHD** [comment]
Hmm...

Can you check if the trackpad shows up in System Preferences?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/22156852/89540721-b913c600-d7fd-11ea-9279-7ae8c841abe1.png)
it is shown, but all gestures aren't working.

**Comment by SkyrilHD** [comment]
It's right, not all gestures are working since it's an Alps Trackpad :P And usually we don't expect our trackpads working like MacBook trackpads since their trackpads very much optimised but here is my settings which shows what works and not:

![image](https://user-images.githubusercontent.com/28839925/89544056-f2e6cb80-d801-11ea-9b82-88b07fd661ab.png)

![image](https://user-images.githubusercontent.com/28839925/89544544-8c15e200-d802-11ea-975c-a0c4eaf46541.png)

![image](https://user-images.githubusercontent.com/28839925/89544578-959f4a00-d802-11ea-89fc-b510db6ab4ad.png)

**Comment by ghost** [comment]
Oh i didn't know that. Btw thanks for the support!

**Comment by Lusanta25** [comment]
Oh I had got the same question: thx @SkyrilHD for the explanation
